export const OBJECTS: string[] = [
  "Brick",
  "Paperclip",
  "Shoe",
  "Blanket",
  "Bucket",
  "Rubber band",
  "Newspaper",
  "Wooden spoon",
  "Tennis ball",
  "Empty bottle",
  "Coat hanger",
  "Umbrella",
  "Pencil",
  "Tin can",
  "Cardboard box",
  "Mirror",
  "Ladder",
  "Rope",
  "Pillow",
  "Fork",
  "Sponge",
  "Clothespin",
  "Ice cube tray",
  "Frisbee",
  "Garden hose",
  "Binder clip",
  "Cork",
  "Toothbrush",
  "Rolling pin",
  "Egg carton",
  "Shoelace",
  "Traffic cone",
  "Hubcap",
  "Ruler",
  "Magnifying glass",
  "Battery",
  "Key",
  "Zipper",
  "Straw",
  "Tire",
  "Ping pong ball",
  "Tape roll",
  "Candle",
  "Funnel",
  "Mug",
  "Paper bag",
  "Chopsticks",
  "Suitcase",
  "Skateboard",
  "Bandana",
];

export function getRandomObject(exclude?: string): string {
  const pool = exclude ? OBJECTS.filter((o) => o !== exclude) : OBJECTS;
  return pool[Math.floor(Math.random() * pool.length)];
}
